name: Hello World Workflow
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: |
          echo "Hello World!"
          echo "This is a GitHub Actions workflow!"
