name: Hardware Heroes
on:
  push:
    branches:
      - detect-hardware.py
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Python script
        run: python detect-hardware.py
